package com.api.dao.characters

import com.api.models.*
import com.api.dao.DatabaseFactory.dbQuery
import org.jetbrains.exposed.sql.*
import org.jetbrains.exposed.sql.SqlExpressionBuilder.eq
import org.jetbrains.exposed.sql.transactions.transaction
import kotlin.random.Random
import kotlin.random.nextInt


class CharactersDaoFacadeImpl : CharactersDaoFacade {
    private fun resultRowToCharacter(row: ResultRow): Character = Character(
        id = row[Characters.id],
        name = row[Characters.name],
        description = row[Characters.description],
        imgUrl = row[Characters.imgUrl]
    )

    override suspend fun randomCharacter(): Character? {
        return dbQuery {
            val numberOfCharacters = Characters.selectAll().count()
            val randomNumber = Random.nextInt(1..numberOfCharacters.toInt())
            Characters.select {Characters.id eq randomNumber}.map(::resultRowToCharacter).singleOrNull()
        }
    }

    override suspend fun characterByName(characterName: String): Character? {
        return dbQuery {
            Characters.select {Characters.name eq characterName}.map(::resultRowToCharacter).singleOrNull()
        }
    }

    override suspend fun addCharacter(name: String, description: String, imgUrl: String): Character? {
        return dbQuery {
            val insertStatement = Characters.insert {
                it[this.name] = name
                it[this.description] = description
                it[this.imgUrl] = imgUrl
            }
            insertStatement.resultedValues?.singleOrNull()?.let(::resultRowToCharacter)
        }
    }

    override suspend fun removeCharacter(id: Int): Boolean {
        return dbQuery {
            Characters.deleteWhere {Characters.id eq id}
        } > 0
    }

    override suspend fun editCharacter(id: Int, name: String, description: String, imgUrl: String): Boolean {
        return dbQuery {
            Characters.update({Characters.id eq id}){
                it[this.name] = name
                it[this.description] = description
                it[this.imgUrl] = imgUrl
            }
        } > 0
    }
}

fun insertCharacters(){
    val characters = listOf(
        CharacterContent("The Mandalorian",  "The Mandalorian, also known as Mando or Din Djarin, is a bounty hunter navigating the outer rim of the galaxy in the era after the fall of the Galactic Empire. He unexpectedly becomes the guardian of Grogu, a young Force-sensitive being. He forms a strong bond with Grogu, despite his initial reluctance and conflicting Mandalorian beliefs.", "https://static.wikia.nocookie.net/starwars/images/8/8a/DinDjarinSansHelmet-TMCh16.png/revision/latest?cb=20201221013823"),
        CharacterContent("Grogu",  "Grogu is a young Force-sensitive being that belongs to the same species as Yoda. He was found by The Mandalorian during a bounty hunt on Arvala-7. Grogu forms an unlikely bond with The Mandalorian, becoming his adopted son. Together, they navigate the dangers of the outer rim, facing bounty hunters, Imperial remnants, and other threats.", "https://static.wikia.nocookie.net/starwars/images/4/43/TheChild-Fathead.png/revision/latest?cb=20201031231040"),
        CharacterContent("The Armorer",  "The Armorer is the leader of a hidden Mandalorian tribe called the Children of the Watch. She crafts and repairs Beskar armor and embodies the ancient Mandalorian code and upholds strict traditions. She serves as a moral compass, challenging The Mandalorian and pushing him to confront his inner conflicts.", "https://static.wikia.nocookie.net/starwars/images/7/7e/TheArmorer-TSWB.png/revision/latest?cb=20211225064945"),
        CharacterContent("Bo-Katan Kryze",  "Bo-Katan Kryze is a Mandalorian princess. She was a lieutenant in the Death Watch group and leader of the Mandalore resistance during the Clone Wars. She met The Mandalorian while searching for Moff Gideon and the Darksaber. The two eventually teamed up with their respective tribes and retook the planet of Mandalore.", "https://static.wikia.nocookie.net/starwars/images/d/d6/BoKatanKryze-TMs3.png/revision/latest?cb=20230326215043"),
        CharacterContent("Greef Karga",  "Initially, Greef Karga, was the Guild Master of Bounty Hunters on Nevarro and tried to kill the Mandalorian after he saved Grogu from the Empire. However, after Grogu saved his life, he helped The Mandalorian defeat Moff Gideon and remove the Imperials from Nevarro. Since then he has turned Nevarro into a trade outpost. He provides crucial advice and resources to The Mandalorian and is a staunch defender of Grogu.", "https://static.wikia.nocookie.net/starwars/images/3/3e/GreefKarga-ToppsFinest2023.png/revision/latest?cb=20240129052728"),
        CharacterContent("Ahsoka Tano",  "Once a young Padawan under Anakin Skywalker, Ahsoka Tano is now a seasoned warrior. She met The Mandalorian and Grogu on Corvus. She guided The Mandalorian towards Grogu's destiny and warned him of the dangers Grogu faces. She teamed up with her apprentice Sabine Wren to find Ezra Bridger and tried to stop the return of Grand Admiral Thrawn.", "https://static.wikia.nocookie.net/starwars/images/2/27/Ahsoka-Tano-AG-2023.png/revision/latest?cb=20231009063143"),
        CharacterContent("Boba Fett",  "Once a feared bounty hunter, Boba Fett has carved a new path for himself in the post-Empire galaxy. Boba Fett emerged from the sands of Tatooine with a desire to reclaim his reputation and armor. He forms a strong alliance with Fennec Shand and together they helped the Mandalorian rescue Grogu from Moff Gideon. He is now the Daimyo of Tatooine, seeking respect and control.", "https://static.wikia.nocookie.net/starwars/images/6/62/BobaFettHS-SWI213.png/revision/latest?cb=20230130144603"),
        CharacterContent("Fennec Shand",  "Fennec Shand was once a top-tier mercenary and assassin. She is renowned for her marksmanship and deadly skills. After being saved by Boba Fett, Fennec forms a formidable partnership, serving as his trusted advisor and lieutenant. Fennec develops a loyalty to Boba Fett and his vision for Tatooine's future.", "https://static.wikia.nocookie.net/starwars/images/b/b4/FennecShandHS-TMCh15.png/revision/latest?cb=20201217015151"),
        CharacterContent("Cara Dune",  "Cara Dune is an Alderaanian and an experienced soldier. She used to be a shock trooper in the Alliance to Restore the Republic and was also the marshal of Nevarro for a brief period. She assisted The Mandalorian in rescuing Grogu from Moff Gideon before being recruited by the New Republic Special Forces.", "https://static.wikia.nocookie.net/starwars/images/3/32/CaraDuneS2-EW.png/revision/latest?cb=20200909003912"),
        CharacterContent("Dr. Pershing",  "Dr. Penn Pershing initially worked for the remnants of the Galatic Empire under Moff Gideon. He is an expert in cloning and genetic manipulation. He possesses a deep scientific curiosity but shows willingness to employ unethical methods for Imperial ambitions. He did express discomfort with harming Grogu while performing experiments. He was later captured by the New Republic and entered their amnesty program.", "https://static.wikia.nocookie.net/starwars/images/b/bd/DrPershing-SignatureSeries2022.png/revision/latest?cb=20231204063948"),
        CharacterContent("Moff Gideon",  "Moff Gideon was a cunning and ruthless leader of an Imperial remnant. He was obsessed with capturing Grogu as he believed his blood held the key to creating powerful clones. He was driven by a desire for control and personal gain. He eventually met his fate while fighting the Mandalorian resistance on Mandalore.", "https://static.wikia.nocookie.net/starwars/images/1/16/Gideon_Armored.png/revision/latest?cb=20240129044344"),
        CharacterContent("Thrawn",  "Grand Admiral Thrawn belongs to the Chiss species, know for their analytical minds and blue skin with red eyes. He possess an unmatched intellect and strategic prowess, allowing him to predict and outmaneuver his opponents. He emerges from exile on Peridea, assembling a new force with the help of Morgan Elsbeth. He returns to Dathomir to reunify the Imperial Remnant.", "https://static.wikia.nocookie.net/starwars/images/f/fe/Thrawn_Character_poster.png/revision/latest?cb=20231007163535"),
        CharacterContent("Kuiil",  "Kuiil was an Ugnaught male who lived on Arvala-7. He worked as a vapor farmer, sought peace and possessed extraordinary technical skills. He assisted The Mandalorian repair his ship after it was looted by Jawas. He eventually met his fate by scout troopers while watching over Grogu on Nevarro.", "https://static.wikia.nocookie.net/starwars/images/f/f1/Kuiil-TMH.png/revision/latest?cb=20230806015644"),
        CharacterContent("IG-11",  "IG-11 was initially a bounty hunter droid, known for its mercilessness and advanced killing capabilities. He was later reprogrammed by Kuiil in order to assist him at his moisture farm. IG-11 later sacrificed himself via self-destruction in order to kill a platoon of stormtroopers to prevent Grogu from being captured. He was later reconstructed and given the position of marshal of Nevarro.", "https://static.wikia.nocookie.net/starwars/images/2/2c/MarshalIG-11.jpg/revision/latest?cb=20230425134709"),
        CharacterContent("Peli Motto",  "Peli Motto is a vibrant and resourceful mechanic who manages Hangar 3-5 at Mos Eisley spaceport on Tatooine. She is renowned for her ability to repair and refuel starships. She is often surrounded by dismantled parts and tools, showcasing her love for tinkering and problem-solving. She develops a friendship with The Mandalorian and Grogu, offering them shelter, repairs, and even moral support.", "https://static.wikia.nocookie.net/starwars/images/2/21/PeliMotto-TMH.png/revision/latest?cb=20230805221415"),
        CharacterContent("Baylan Skoll",  "Baylan Skoll is a former Jedi Knight who managed to survive the Great Jedi Purge. He is driven by a passionate belief that the Jedi failed the galaxy, he seeks to destroy the existing order and rebuild it in a new form. Him and his apprentice, Shin Hati, were allied with forces of Morgan Elsbeth and together they aided the return of Grand Admiral Thrawn. After Thrawn's return, Skoll continued his search for his destiny on Peridea.", "https://static.wikia.nocookie.net/starwars/images/9/9f/BaylanSkoll-YearInReview2023.png/revision/latest?cb=20231214004047"),
        CharacterContent("Morgan Elsbeth",  "Morgan Elsbeth was a Nightsister and an industrialist. She was the cruel and tyrannical magistrate of Calodan on the planet Corvus. She was defined by ambition and ruthlessness. She retrieved a star map which led her directly to Grand Admiral Thrawn on Peridea. Ultimately, she was defeated by Ahsoka on Peridea.", "https://static.wikia.nocookie.net/starwars/images/4/4e/MorganElsbeth-YearInReview2023.png/revision/latest?cb=20231214004622"),
        CharacterContent("Huyang",  "Huyang is a Mark IV architect droid who has served the Jedi Order for centuries as a lightsaber architect. He has guided younglings through the process of constructing their personal blades. His expertise extends beyond technical know-how, embodying the Jedi philosophy. He assisted Ahsoka and Sabine Wren on their mission to find Ezra Bridger.", "https://static.wikia.nocookie.net/starwars/images/8/8c/Huyang-AhsokaPoster.png/revision/latest?cb=20230826072220"),
        CharacterContent("Paz Vizsla",  "Paz Vizsla was a fierce Mandalorian warrior, loyal to his clan and customs. He was a member of the Children of the Watch and initially had clashes with the Mandalorian. After The Mandalorian and Bo-Katan rescued his son, he agreed to help them free Nevarro from pirates. He was eventually killed in action while holding the line against Moff Gideon's armored commandos and Praetorian Guards.", "https://static.wikia.nocookie.net/starwars/images/f/fc/PazVizsla-CEUEE.png/revision/latest?cb=20211218023744"),
        CharacterContent("Carson Teva",  "Captain Carson Teva is a dedicated captain within the Adelphi Rangers of the New Republic Starfighter Corps. Carson Teva is fiercely protective of the fragile peace following the Empire's fall. He was initially wary of The Mandalorian but later provides advice and assistance. The Mandalorian later offers his help to Carson to hunt down Imperial remnants.", "https://static.wikia.nocookie.net/starwars/images/a/ad/Carson_Teva_MandoS3.png/revision/latest?cb=20230402082534"),
        CharacterContent("Cobb Vanth",  "Cobb Vanth is the sheriff and mayor of Mos Pelgo, which was eventually renamed Freetown. He met The Mandalorian who came to Mos Pelgo searching for a fellow Mandalorian. At that time, Vanth was wearing Boba Fett's armor and agreed to give it to The Mandalorian if he assisted him in defeating a Krayt dragon. Later, when the Pyke Syndicate were attempting to takeover Tatooine, Vanth was shot by Cad Bane. Once the Pyke Syndicate were defeated, Cobb Vanth started receiving treatment.", "https://static.wikia.nocookie.net/starwars/images/4/42/Cobb-Vanth-AG.png/revision/latest?cb=20230902204554"),
        CharacterContent("Mayfeld",  "Migs Mayfeld is a mercenary and former sharpshooter of the Imperial Army. He was recruited by Ranzar Malk, to work in a team which included The Mandalorian, to rescue a prisoner. During the mission he had betrayed Din Djarin but then was later defeated by him. Later, The Mandalorian required his assistance in finding Moff Gideon's ship and was subsequently set free by Cara Dune.", "https://static.wikia.nocookie.net/starwars/images/0/0a/MigsMayfeld-TMH.png/revision/latest?cb=20230805211215"),
        CharacterContent("Shin Hati",  "Shin Hati is the apprentice of Baylan Skoll and together they worked with Morgan Elsbeth to find Grand Admiral Thrawn. Hati eventually questioned her master and their paths went separate ways. In the end, she was left stranded on Peridea.", "https://static.wikia.nocookie.net/starwars/images/7/71/Shin_Hati_profile.png/revision/latest?cb=20231007072117"),
        CharacterContent("Sabine Wren",  "Sabine Wren is a female Mandalorian warrior and has the ability to use the Force. She was initially recruited by Hera Syndulla and Kanan Jarrus to join their rebel crew and was able to help them liberate the planet of Lothal from the Imperials. She later became the apprentice of Ahsoka Tano but Ahsoka parted ways with her. Ahsoka eventually returned to her and together they went on a journey to find Ezra Bridger and stop the return of Thrawn. In the end, both were left stranded on Peridea.", "https://static.wikia.nocookie.net/starwars/images/c/cc/Sabine_Wren-AG.png/revision/latest?cb=20230802103304"),
        CharacterContent("Luke Skywalker",  "Luke Skywalker is a legendary Jedi Master who fought against the Empire alongside Princess Leia Organa and Han Solo. He later rescued Grogu from Moff Gideon's forces and temporarily took him as his apprentice on Ossus. Luke eventually offered Grogu a choice of which Grogu chose to return to The Mandalorian.", "https://static1.cbrimages.com/wordpress/wp-content/uploads/2023/02/luke-skywalker-grogu-the-book-of-boba-fett.jpg"),
        CharacterContent("Anakin Skywalker",  "Anakin Skywalker was a legendary Jedi Knight and eventually became Darth Vader. During the Clone Wars, he oversaw the training of his apprentice, Ahsoka Tano. They both met again in the World Between Worlds, a mystical dimension within the Force that touches every point of time and space, where Anakin had one final lesson to teach Ahsoka.", "https://legendary-digital-network-assets.s3.amazonaws.com/wp-content/uploads/2023/09/06092615/Anakin-Skywalker-Ahsoka.jpg"),
        CharacterContent("Ezra Bridger",  "Ezra Bridger is a Bokken Jedi who was taught the ways of the Force by Kanan Jarrus. He managed to liberate his home world of Lothal from Imperial control but him and Grand Admiral Thrawn were taken into hyperspace by the Purrgil. He was eventually found by Sabine Wren and Ahsoka on Peridea but left them behind while he escaped on Thrawn's Star Destroyer.", "https://static.wikia.nocookie.net/starwars/images/a/ad/Ezra_Bridger_character_poster.png/revision/latest?cb=20231004192907"),
        CharacterContent("Hera Syndulla",  "Hera Syndulla is a strong female leader and was a member of the Ghost crew. She continued to help Ahsoka in her hunt for Thrawn and continued to warn the New Republic of the dangers of Thrawn's return.", "https://static.wikia.nocookie.net/starwars/images/4/46/Hera_Syndulla-AG.png/revision/latest?cb=20230802102106"),
        CharacterContent("Great Mothers",  "The Great Mothers are the three Dathomirian Nightsisters who allied with Grand Admiral Thrawn. They are particular skilled in reading threads of fate and destiny. Their names are Klothow, Aktropaw and Lakesis", "https://static.wikia.nocookie.net/starwars/images/2/20/GreatMothersCroppedPoster.png/revision/latest?cb=20230922052742"),
        CharacterContent("Cad Bane",  "Cad Bane was a Duros male bounty hunter. He was infamous during the Clone Wars, known for fighting Jedis such as Obi-Wan Kenobi and Anakin Skywalker. He was later hired by the Pyke Syndicate to assist them to takeover Tatooine but was eventually killed by Boba Fett.", "https://static.wikia.nocookie.net/starwars/images/9/97/CadBane-AG.png/revision/latest?cb=20221205044134"),
        CharacterContent("Axe Woves",  "Axe Woves is a male Mandalorian who worked alongside Koska Reeves and Bo-Katan Kryze. The three of them plus The Mandalorian were able to steal an Imperial cruiser on Trask. Later, Woves was part of the resistance to reclaim the planet of Mandalore.", "https://static.wikia.nocookie.net/starwars/images/9/9e/AxeWoves-AG.png/revision/latest?cb=20231214005844"),
        CharacterContent("Elia Kane",  "Elia Kane is a comms officer that worked for Moff Gideon. She was captured by the New Republic and placed in their Amnesty Program. However, she remained devoted to the cause of the Empire, and secretly continued to take directions from Moff Gideon.", "https://static.wikia.nocookie.net/starwars/images/9/99/EliaKane-SWCT.png/revision/latest?cb=20230827041131"),
        CharacterContent("Koska Reeves",  "Koska Reeves is a female Mandalorian who helped steal the Imperial cruiser alongside Bo-Katan Kryze, Axe Woves and Din Djarin on Trask. Later, she was part of the Mandalorian resistance to reclaim the planet of Mandalore.", "https://static.wikia.nocookie.net/starwars/images/f/fd/KoskaReeves-TMCh11.png/revision/latest?cb=20220304023513"),
        CharacterContent("Mok Shaiz's Majordomo",  "Mok Shaiz's Majordomo is the majordomo of the mayor of Mos Espa, Mok Shaiz. He continuously lied to Boba Fett and Fennec Shand about the mayor to protect the mayor's secrecy but was eventually captured by the Daimyo.", "https://static.wikia.nocookie.net/starwars/images/d/dd/TwilekMajordomo-Platinum2023.png/revision/latest?cb=20230902205200"),
        CharacterContent("The Client",  "The Client was part of the Imperial remnant led by Moff Gideon. He operated from a safe house in Nevarro alongside Dr. Pershing and had hired The Mandalorian to find Grogu. He was ordered to extract blood from Grogu for Gideon's cloning project. He was eventually killed by Moff Gideon's men.", "https://static.wikia.nocookie.net/starwars/images/c/c7/TheClient-SWCT.png/revision/latest?cb=20231022173409"),
        CharacterContent("Frog Lady",  "The Frog Lady was assisted by The Mandalorian who escorted her to Trask as she had eggs that needed to be fertilized by her husband. She has strong technical skills as she was able to repair a droid so that she could communicate with The Mandalorian while they had crashed on Maldo Kreis.", "https://static.wikia.nocookie.net/starwars/images/8/87/FrogLady-TMH.png/revision/latest?cb=20220510060751"),
        CharacterContent("Hutt Twins",  "The Hutt Twins are the cousins of Jabba the Hutt and had sent Krrsantan to kill Boba Fett as they had laid claim on Jabba's territory. They had apologised to Boba Fett after Krrsantan's failure and had gifted him a Rancor.", "https://static.wikia.nocookie.net/starwars/images/6/61/The-Twins-Hutts-Boba-Espa.png/revision/latest?cb=20220126032555"),
        CharacterContent("Garsa Fwip",  "Garsa Fwip was the owner of the Sanctuary, a cantina on Mos Espa. She was ensured the longevity of her business by Boba Fett. She was eventually killed after the Sanctuary was bombed by the Pyke Syndicate.", "https://static.wikia.nocookie.net/starwars/images/2/28/GarsaFwip-BoBFCh4.png/revision/latest?cb=20221129061646"),
        CharacterContent("Jacen Syndulla",  "Jacen is the Force-sensitive son of Genral Hera Syndulla and late Jedi Knight Kanan Jarrus.", "https://static.wikia.nocookie.net/starwars/images/0/04/JacenSyndulla-AhsokaPoster.png/revision/latest?cb=20230902095624"),
        CharacterContent("Mon Mothma",  "Mon Mothma was a female politician and revolutionary leader. During the time of the Galactic Empire, she had a seat in the Imperial Senate but had organized underground resistance groups alongside Luthen Rael and senator Bail Organa. She is now the Chancellor of the New Republic.", "https://static.wikia.nocookie.net/starwars/images/2/22/Mon_Mothma_Ahsoka_poster.png/revision/latest?cb=20230904071259"),
        CharacterContent("Marrok",  "Marrok was a mercenary and an Inquisitor who was hired by Morgan Elsbeth to aid her in her quest to find Grand Admiral Thrawn. He eventually met his fate by Ahsoka Tano on Seatos.", "https://static.wikia.nocookie.net/starwars/images/6/68/Marrok-AG.png/revision/latest?cb=20230919050834"),
        CharacterContent("Enoch",  "Enoch is Grand Admiral Thrawn's Captain of the Guard.", "https://static.wikia.nocookie.net/starwars/images/7/70/Enoch-Ahsokacharacterposter.png/revision/latest?cb=20230922055350"),
        CharacterContent("Toro Calican",  "Toro Calican was a bounty hunter who wanted to get into the Bounty Hunters' Guild. He was on the hunt for Fennec Shand and took the assistance of The Mandalorian to find her. He then decided to turn the The Mandalorian in to the Guild but was eventually killed by him on Tatooine.", "https://static.wikia.nocookie.net/starwars/images/e/e5/ToroCalican-TMH.png/revision/latest?cb=20220510055435"),
        CharacterContent("Ranzar Malk",  "Ranzar Malk is a crime boss that operated from the Roost Space Station and was the former partner of The Mandalorian. He had put together a crew of mercenaries to breakout a prisoner from a New Republic prison ship.", "https://static.wikia.nocookie.net/starwars/images/4/43/RanzarMalk-TMH.png/revision/latest?cb=20230805205151"),
        CharacterContent("Xi'an",  "Xi'an is a Twi'lek female mercenary. She was hired by Ranzar Malk to work with The Mandalorian and other mercenaries to rescue her twin brother, Qin.", "https://static.wikia.nocookie.net/starwars/images/5/57/Xian-CEUEEd.png/revision/latest?cb=20220509235230"),
        CharacterContent("Bib Fortuna",  "Bib Fortuna was Jabba the Hutt's majordomo. After Jabba's death, he assumed control of Jabba's territory and palace as the new crime boss. He was killed by Boba Fett who then became the new Daimyo.", "https://static.wikia.nocookie.net/starwars/images/1/12/BibFortuna-CEUEEd.png/revision/latest?cb=20220507185048"),
        CharacterContent("8D8",  "8D8 is a Roche Hive 8D-series smelter droid who was the chief of Cyborg Operations for Jabba the Hutt. He later worked for Boba Fett.", "https://static.wikia.nocookie.net/starwars/images/2/2d/8D8_BoBF.png/revision/latest?cb=20221018165206"),
        CharacterContent("Mayor Mok Shaiz",  "Mok Shaiz was the mayor of Mos Espa. After Boba Fett became the new Daimyo, Shaiz had offered Fett's territory to the Pyke Syndicate. He was later killed by Fennec Shand while in hiding with the other crime bosses of Mos Espa.", "https://static.wikia.nocookie.net/starwars/images/e/e7/MokShaiz-ChromeGalaxy2022.png/revision/latest?cb=20231201014047"),
        CharacterContent("Skad",  "Skad was a member of a street gang on Mos Espa. The gang stole water but were later confronted by Boba Fett who offered them to work for him. The gang members were involved in fighting Krrsantan and chasing Mok Shaiz's Majordomo through Mos Espa. He later staked out the spaceport for reconnaissance, catching the arrival of the Pyke Syndicate operatives and reporting this to Boba and Fennec Shand", "https://static.wikia.nocookie.net/starwars/images/2/22/Skad-BOBFC3.png/revision/latest?cb=20221129060001"),
        CharacterContent("Drash",  "Drash was a member of a street gang on Mos Espa. The gang stole water but were later confronted by Boba Fett who offered them to work for him. The gang members were involved in fighting Krrsantan and chasing Mok Shaiz's Majordomo through Mos Espa. She was later involved in fighting the Pyke Syndicate on the streets of Mos Espa.", "https://static.wikia.nocookie.net/starwars/images/5/52/Drash-BOBFC3.png/revision/latest?cb=20220129050408"),
        CharacterContent("Rancor Keeper",  "The Rancor Keeper was hired by Boba Fett to assist him with taking care of a Rancor that was gifted to him by the Hutt Twins.", "https://static.wikia.nocookie.net/starwars/images/6/63/RancorKeeper-Inception2022.png/revision/latest?cb=20231215053157"),
        CharacterContent("Krrsantan",  "Krrsantan is a Wookiee bounty hunter that was orignally hired by Jabba the Hutt and Darth Vader. He was later hired by the Hutt Twins to assassinate Boba Fett but was eventually employed by Fett. He was part of Fett's forces that fought against the Pyke Syndicate.", "https://static.wikia.nocookie.net/starwars/images/f/f7/Krrsantan-SWI212.png/revision/latest?cb=20230128065831"),
        CharacterContent("Pyke Boss",  "The Pyke Boss was the boss of the Pyke Syndicate's operation on Tatooine. He had lied to Boba Fett after Fett had demanded a protection fee for the Tusken Raiders as a fee was already paid to the Nikto bikers. The Pyke Boss boss had the Tusken tribe destroyed and framed the Nikto bikers, which Fett took revenge on. The Pyke Boss was eventually killed by Fennec Shand.", "https://static.wikia.nocookie.net/starwars/images/1/10/PykeBoss-Villains2023.png/revision/latest?cb=20231015172818"),
        CharacterContent("The Anzellan",  "The Anzellan is a droidsmith on Nevarro who was tasked alongside two other Anzellans to fix IG-11 by Greef Karga and The Mandalorian.", "https://static1.colliderimages.com/wordpress/wp-content/uploads/2023/03/anzellans-mandalorian-season-3.jpg?q=50&fit=crop&w=1500&dpr=1.5"),
        CharacterContent("Gorian Shard",  "Gorian Shard was a Pirate King of a gang of pirates. Gorian Shard and his pirate forces had taken over Nevarro but were later defeated by The Mandalorian, Bo-Katan Kryze and other Mandalorians. Gorian met his fate during the battle.", "https://static.wikia.nocookie.net/starwars/images/1/18/Gorian_Shard.png/revision/latest?cb=20230308224217"),
        CharacterContent("Captain Bombardier",  "Captain Bombardier was a planning officer for the Empire. As part of the New Republic's Amnesty Program, he helped rebuild Plazir-15 and during the process fell in love with the Duchess who was a member of the royal family. Together they formed an absolute democracy. Bombardier later hired The Mandalorian and Bo-Katan Kryze to investigate why reprogrammed Imperial droids used for civic service on Plazir-15 began malfunctioning and posing a threat to its citizens.", "https://static.wikia.nocookie.net/starwars/images/0/04/CaptainBombardier-Mando22.png/revision/latest?cb=20230405153701"),
        CharacterContent("The Duchess",  "The Duchess is the wife of Captain Bombardier and together they rule over Plazir-15.", "https://static.wikia.nocookie.net/starwars/images/4/4e/The_Dutchess_Lizzo_MandoS3.png/revision/latest?cb=20230425083819"),
        )

    transaction {
        Characters.batchInsert(characters){
            (name, description, imgUrl) ->
            this[Characters.name] = name
            this[Characters.description] = description
            this[Characters.imgUrl] = imgUrl
        }
    }
}

val charactersDAO = CharactersDaoFacadeImpl().apply {
   insertCharacters()
}