on:
  pull_request:
    branches:
      - master
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10
    types:
      - closed

name: Create Release

jobs:
  build:
    name: Create Release
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MANDALORIAN_API_RELEASE_TOKEN }}
        with:
          tag_name: v1.0.1
          release_name: v1.0.1
          body: |
            Fix: Removed unnecessary URI path in nginx config, added primary key to users model and added return@verbs and if and else blocks to prevent code from going beyond validations and checks.
          draft: false
          prerelease: false